### ISSUE TITLE
농삿물 캐기오류

### ISSUE THREAD

**Issue by newkincode** [newkincode/simple_farming_game#2]
맵밖에서 캔거아닌데 리스트를 넘어섰다고함
Traceback (most recent call last):
  File "c:\Users\gongb\OneDrive\바탕 화면\새 폴더\simple_farming_game\main.py", line 101, in <module>
    keyin.key(selectImg,riceClass,farmRiceImg,screen,playerTilePos,stop,delRice,riceSerci,playerClass)
  File "c:\Users\gongb\OneDrive\바탕 화면\새 폴더\simple_farming_game\file\code\keyinput.py", line 34, in key
    delrice(playerTilePos[1],playerTilePos[0])
  File "c:\Users\gongb\OneDrive\바탕 화면\새 폴더\simple_farming_game\main.py", line 75, in delRice
    if (riceClass[i].tilePos[1]/32 == x) and (riceClass[i].tilePos[0]/32 == y):
IndexError: list index out of range
좌표:23,1
오류번호:1(16진수)

**Comment by newkincode** [comment]
해결
