### ISSUE TITLE
`IndexError: list index out of range`

### ISSUE THREAD

**Issue by ky0422** [newkincode/simple_farming_game#6]
```
Traceback (most recent call last):
  File "...\main.py", line 106, in <module>
    keyin.key(selectImg, riceClass, farmRiceImg, screen,playerTilePos, stop, delRice, riceSerci, playerClass,reload)
  File "...\keyinput.py", line 44, in key
    case pygame.K_d: key_d()
                     ^^^^^^^
  File "...\keyinput.py", line 30, in key_d
    delrice(playerTilePos[1], playerTilePos[0])
  File "...\main.py", line 78, in delRice
    if (riceClass[i].tilePos[1]/32 == x) and (riceClass[i].tilePos[0]/32 == y):
        ~~~~~~~~~^^^
IndexError: list index out of range
```

---

![image](https://user-images.githubusercontent.com/59119316/214060346-91ca6909-a959-4fb5-9310-e7cce7ea66df.png)

다음과 같이 배치되어있는 상태에서, 맨 아래를 제외한 나머지를 삽(S) 으로 사용(D) 했을때, 위와 같은 오류가 발생합니다.

---

사용 환경: Windows 11, Python 3.11, Pygame latest (pre)

**Comment by newkincode** [comment]
아뭐야TQ아직 안고쳐진걸 그냥 클로즈해버림ㅋㅋ

**Comment by newkincode** [comment]
좌표도 주세요
오류코드:3
